### ISSUE TITLE
USB監視終了を複数回コールした場合について考慮されていない

### ISSUE THREAD

**Issue by ko-matsu** [cryptogarageinc/ledger-liquid-lib#19]
# Overview

- node-usb-detectionのためnode-hidのverupには関係ないはずだが、既存の潜在タイミング問題である可能性からIssueにあげておく。
  - https://www.npmjs.com/package/usb-detection#usbdetectstopmonitoring
  - 修正自体は内部フラグ(isStartMonitoring)をfalseにするだけで良い。
    - https://github.com/cryptogarageinc/ledger-liquid-lib/blob/v0.1.4/src/ledger-liquid-lib.js#L858-L860
    - 4/13AMに対応する。

# Sub tasks

- [ ] 修正および動作確認 (1.0h -> )

# Completion condition

- 既存のUSB監視動作に影響がないこと。

**Comment by k-matsuzawa** [comment]
0e7c1e3 で対応。クローズする。
