### ISSUE TITLE
pegout by Ledger

### ISSUE THREAD

**Issue by k-matsuzawa** [cryptogarageinc/ledger-liquid-lib#27]
# Overview

- Support pegout of Ledger, and at the same time, have ScriptPubkey split and sent.

# Sub tasks

- [x] Impl
- [ ] Check

# Completion condition

- [ ] Can create a signature for a pegged-out transaction.

**Comment by ko-matsu** [comment]
上限値
[testdata.txt](https://github.com/cryptogarageinc/ledger-liquid-lib/files/7591773/testdata.txt)

**Comment by ko-matsu** [comment]
maximum pegout scriptPubkey transaction data.
[testdata.txt](https://github.com/cryptogarageinc/ledger-liquid-lib/files/7591785/testdata.txt)

**Comment by ko-matsu** [comment]
execute test by debug firmware ( https://developers.ledger.com/docs/nano-app/debug/ )
```
npm run ts_example -- -peg
  (omission of middle part of a text)
sendHashInputStartCmd send ->  e0440006050200000001
sendHashInputStartCmd send ->  e04480062f0303ae7c6c1dac6f9b83c100e5bbad2e6262ae3f1932ede271150aa0613e7a5099000000000100000000000f3e5800
sendHashInputStartCmd send ->  e044800604ffffffff
sendHashInputFinalizeFullCmd send ->  e04a00000103
sendHashInputFinalizeFullCmd send ->  e04a00002a0125b251070e29ca19043cf33ccd7324e2ddab03ecc4ae0b5e77c4fc0e5cf6c95a01000000000007a120
sendHashInputFinalizeFullCmd send ->  e04a00000100
sendHashInputFinalizeFullCmd send ->  e04a00000100
sendHashInputFinalizeFullCmd send ->  e04a0000bec16a2006226e46111a0b59caaf126043eb5bbf28c34f3a5e332a1fc7b2b73cf188910f1976a9146fa03ec68aaeef6f429ad9267f29ae98d0d2b58b88ac21031797e767f8ea79110c2d911379ef8210ccaba0f06a0721a1c570806305b31b0a4c6102b52d98d53b15559358aa0e037f77ce6eeb10cb58e8aafc6799fa20b2f0525cb155005226b39ba21881e8afb5c8a0330c58f7b7337bbe4d88ae03e9d6e446076a83aecf7a46e25c8a37ed81aacf5872463d48c241f7ab5b7d865faddf
sendHashInputFinalizeFullCmd send ->  e04a0000043cf0c54c
sendHashInputFinalizeFullCmd recv:  20a1070000000000c16a2006226e46111a0b59caaf126043eb5bbf28c34f3a5e332a1fc7b2b73cf188910f1976a9146fa03ec68aaeef6f429ad9267f29ae98d0d2b58b88ac21031797e767f8ea79110c2d911379ef8210ccaba0f06a0721a1c570806305b31b0a4c6102b52d98d53b15559358aa0e037f77ce6eeb10cb58e8aafc6799fa20b2f0525cb155005226b39ba21881e8afb5c8a0330c58f7b7337bbe4d88ae03e9d6e446076a83aecf7a46e25c8a37ed81aacf5872463d48c241f7ab5b7d865faddf6a80
```
error response:
20a1070000000000c16a2006226e46111a0b59caaf126043eb5bbf28c34f3a5e332a1fc7b2b73cf188910f1976a9146fa03ec68aaeef6f429ad9267f29ae98d0d2b58b88ac21031797e767f8ea79110c2d911379ef8210ccaba0f06a0721a1c570806305b31b0a4c6102b52d98d53b15559358aa0e037f77ce6eeb10cb58e8aafc6799fa20b2f0525cb155005226b39ba21881e8afb5c8a0330c58f7b7337bbe4d88ae03e9d6e446076a83aecf7a46e25c8a37ed81aacf5872463d48c241f7ab5b7d865faddf 
6a80 (error code)

**Comment by k-matsuzawa** [comment]
add currently success pattern test. `npm run ts_example -- -okpeg`

**Comment by k-matsuzawa** [comment]
fixed app-bitcoin (based liquid branch).
https://github.com/cryptogarageinc/app-bitcoin/tree/feature/support-pegout

I will now test the impact of the fix.

**Comment by k-matsuzawa** [comment]
>fixed app-bitcoin (based liquid branch).
https://github.com/cryptogarageinc/app-bitcoin/tree/feature/support-pegout

Changes in this branch:
- Added support for splitting the large OP_RETURN script and loading it.
